version: 2
updates:
  - package-ecosystem: github-actions
    directory: ""
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: devcontainers
    directory: ""
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: ""
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: ""
    target-branch: develop
    schedule:
      interval: weekly
